### ISSUE TITLE
Update binary trie with new data structure

### ISSUE THREAD

**Issue by NIC619** [ApeWorX/py-trie#37]
As proposed and discussed in [ethresearch](https://ethresear.ch/t/data-availability-proof-friendly-state-tree-transitions/1453/6), Binary Trie built on Sparse Merkle Tree has the advantage that it's more simple and straight forward(there only exist one node type - branch node, just like plain Binary Tree) while size of merkle proof is roughly the same(or even slightly better) since most subtree in Sparse Merkle Tree would be empty and we can compress these nodes into 1 bit representation.

The cost is that it takes O(log(N)) time to `get`/`set` value. In our case(with 2^160 address space) it's 160 nodes to traverse to get to the leaf node, but there should be room for optimization.

**Comment by fubuloubu** [comment]
@NIC619 check out #77
