### ISSUE TITLE
Update to use `eth_utils.toolz` indirection for imports

### ISSUE THREAD

**Issue by pipermerriam** [ApeWorX/py-trie#70]
### What is wrong?

This library currently specifies `cytoolz` as a hard dependency.  This makes pypy support more difficult.

### How can it be fixed?

- Remove `cytoolz` from the direct dependencies.
- Update the `eth-utils` requirement to be `>=1.3.0,<2`
- Update all imports that come from `cytoolz` to instead come from `eth_utils.toolz`

**Comment by 6ug** [comment]
I am on it!

**Comment by Bhargavasomu** [comment]
@pipermerriam , as I have not seen any progress on this issue, I have worked on this and fixed this. Please review #76 for merging.

**Comment by Bhargavasomu** [comment]
Also eth-utils 1.3.0 is in beta phase, and have added the same name in the setup.
