### ISSUE TITLE
Proving absence of a key

### ISSUE THREAD

**Issue by carver** [ApeWorX/py-trie#88]
### What was wrong?

One might like to prove that a key is *absent* from a trie with `get_proof()`. (Or maybe a separate API to avoid confusion)?

Right now it just crashes if you try to get a proof for a key that's not in the trie.

### What did you expect it to do?

Add a new method `get_absence_proof()` (or something like it) that uses the trie nodes to prove that a key doesn't exist.

**Comment by mttbernardini** [comment]
I think this is unintended or just not implemented yet, as in test case [`test_get_from_proof_key_does_not_exist()`](https://github.com/ethereum/py-trie/blob/5e989eedd6ffd5c5d35d3ad1809817362e6ee181/tests/test_proof.py#L16) it is shown how a proof is used to verify a key which is __absent__ from the original trie.

I think the right approach would be to make `get_proof` return the needed trie nodes to prove a key is absent, as shown in the test case.

Here's a dump of the proof in the used fixture:
![graph](https://user-images.githubusercontent.com/14125973/56199728-c7a10180-603d-11e9-8818-35eedf2a4114.png)

In the test case there's a `get_from_proof` for key `0x41b1a0649752af1b28b3dc29a1556eee781e4a4c3a1f7f53f90fa834de098c4d`. As you can see from the image the path stops at `0x41b1a0` and then diverges, but the final leaf node is sufficient to determine that the key is not present. The way it is implemented is that a `get` for that key will simply return an empty binary string `b''`.

I'm looking forward to implement this feature as it is needed for my work, eventually I'll make a PR if it is welcome.

**Comment by carver** [comment]
> I think this is unintended or just not implemented yet, as in test case [`test_get_from_proof_key_does_not_exist()`](https://github.com/ethereum/py-trie/blob/5e989eedd6ffd5c5d35d3ad1809817362e6ee181/tests/test_proof.py#L16) it is shown how a proof is used to verify a key which is **absent** from the original trie.

Right, thanks for pointing this out, it's good to be more specific. Evaluating the proof (via `get_from_proof()`) doesn't need to change. That's already working as intended. We only need to add the ability to conveniently create a proof for a missing key. :+1:

> I'm looking forward to implement this feature as it is needed for my work, eventually I'll make a PR if it is welcome.

PR definitely welcome!

I'm a bit ambivalent between two APIs, with maybe a slight preference for the latter):
- `get_exclusion_proof(` (or instead of `exclusion`: `missing`, `absence`, etc)
- `get_proof(key, *, missing=False)` (so that it would fail by default if the key is missing, but you could explicitly allow it if you want)

In either case, the proof building should fail if the key is expected to be missing but is actually present.

**Comment by mttbernardini** [comment]
Thank you for the reply.

Am I missing something, or is it the aim of the proof to determine and prove wheter a key has a specific value or if at all (= is absent)?

In that case I would disagree with either API and I'd prefer just to leave it as is but never raise, leaving the check to the caller as already done when verifying a traditional value by `assert get_from_proof(root_hash, key, proof) == expected_value`.

> In either case, the proof building should fail if the key is expected to be missing but is actually present.

I think this is out of the scope of `get_proof`, as I said above that's the job of the check done with `get_from_proof`, as there's no notion of "expected thing" when calling `get_proof` but afterwards when comparing the value with `get_from_proof`.

However there's one thing to point out: the actual implementation of `get` doesn't distinguish between an empty value vs absent key, as in the latter case it will also return an empty value. Maybe returning `None` would be more correct? But that's just my thinking, I don't know if the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) expects this kind of distinction.

**Comment by carver** [comment]
> In that case I would disagree with either API and I'd prefer just to leave it as is but never raise

Hm, I guess I'm open to it. The stricter method probably just leads to workarounds like `trie.get_proof(key, missing=(key not in trie))`.

> 

> However there's one thing to point out: the actual implementation of `get` doesn't distinguish between an empty value vs absent key, as in the latter case it will also return an empty value. Maybe returning `None` would be more correct? But that's just my thinking, I don't know if the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) expects this kind of distinction.

Yeah, I would consider it a bug to have an explicit empty leaf value. `Absent == Empty` in (Ethereum Hexary) tries. Getting a missing key should continue returning `b''`.

**Comment by carver** [comment]
We encourage opening PR very early (way before you're happy with the code) so that we can give early feedback before you get into the cleanup of things like docs/tests/lint.

**Comment by mttbernardini** [comment]
I'll open the PR tomorrow at work, I've already implemented the feature the way I described it (never raising) and added a couple of tests.

The fact that `Absent == Empty` is kinda funny, because this way different tries representing the same data can exists with different root-hashes, as conceptually not having a key would be the same as having a key with an empty value, but structurally it could be of course different. But if that's the spec I'm fine with it, just an opinion, not even an actual problem ;)
