### ISSUE TITLE
Use latest snake-charmers tooling

### ISSUE THREAD

**Issue by carver** [ApeWorX/py-trie#99]
### What was wrong?

Not merged with our project template, so missing a lot of the goodies we might like to have in place.

### How to fix

Merge in the template, allowing unrelated branches. And fix the invariable flood of problems. Almost certainly disable mypy, for example. Probably want to figure out how to skip downloading the `fixtures` submodule when building at readthedocs, because it's huge and unnecessary.

Also, add in a note here about how to do that ^ merge for the first time with an existing project:
https://github.com/ethereum/snake-charmers-tactical-manual/blob/master/template.md

**Comment by pacrob** [comment]
`py-trie` is now on the template update train :steam_locomotive:
